spring.application.name=exemplo1N
# Ligação com o banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/projetoDS3
# Usúario padrão da maquina e senha
spring.datasource.username=root
spring.datasource.password=123456
# Driver utilizado
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Para ver o sql que está executando, os comandos sendo executados no back
spring.jpa.properties.hibernate.show_sql=true
# Faz que de um uodate no banco em vez de criar ele novamente, cria altomaticamente
spring.jpa.hibernate.ddl-auto=update
# Para mostrar o sql de forma estruturada e mostrar ele formatado
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Comando para criar no MySQL Workbanch => create database projetoDS3;